services:
  db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - ./mariadb_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped